export const storeProducts = [
    {
        id: 1,
        title: "Samsung blade - Gray",
        img: "img/applecomp1.jpg",
        price: 56500,
        company: "dufuna",
        info: "Empower and engage young people to see JCI as the platform where they can peacefully work together with likeminded people for the sustainable development of their communities.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 2,
        title: "Samsung Razor - Black",
        img: "img/computers3.jpg",
        price: 56500,
        company: "dufuna",
        info: "Empower and engage young people to see JCI as the platform where they can peacefully work together with likeminded people for the sustainable development of their communities.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 3,
        title: "Samsung Gum - Gray",
        img: "img/hp.png",
        price: 56500,
        company: "dufuna",
        info: "Empower and engage young people to see JCI as the platform where they can peacefully work together with likeminded people for the sustainable development of their communities.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 4,
        title: "Nokia blade - Gray",
        img: "img/phone1.jpg",
        price: 56500,
        company: "dufuna",
        info: "Empower and engage young people to see JCI as the platform where they can peacefully work together with likeminded people for the sustainable development of their communities.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 5,
        title: "Techno blade - Gray",
        img: "img/phone2.jpg",
        price: 56500,
        company: "dufuna",
        info: "Empower and engage young people to see JCI as the platform where they can peacefully work together with likeminded people for the sustainable development of their communities.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 6,
        title: "Samsung Gum - Gray",
        img: "img/hp.png",
        price: 56500,
        company: "dufuna",
        info: "Empower and engage young people to see JCI as the platform where they can peacefully work together with likeminded people for the sustainable development of their communities.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 7,
        title: "Samsung blade - Gray",
        img: "img/applecomp1.jpg",
        price: 56500,
        company: "dufuna",
        info: "Empower and engage young people to see JCI as the platform where they can peacefully work together with likeminded people for the sustainable development of their communities.",
        inCart: false,
        count: 0,
        total: 0,
    },
    {
        id: 8,
        title: "Techno blade - Gray",
        img: "img/phone2.jpg",
        price: 56500,
        company: "dufuna",
        info: "Empower and engage young people to see JCI as the platform where they can peacefully work together with likeminded people for the sustainable development of their communities.",
        inCart: false,
        count: 0,
        total: 0,
    },
]
